name: CI

on: 
  pull_request:
    branches:
    - master
    - develop
  push:
    branches:
    - master
    - develop

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-22.04', 'ubuntu-20.04' ]
        go: [ '~1.18.0' ]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v3

    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get -y install libsofthsm2

    - name: Build & test
      run: |
        go build -v ./...
        go test -short -v ./...
