name: Go
on: [push, pull_request]
jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '~1.18.0' ]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v3

    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get -y install libsofthsm2

    - name: Build & test
      run: |
        go build -v ./...
        go test -v ./...
